//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////

using System.Collections.Generic;
using Server.Network;
using Server.Mobiles;
using Server.Gumps;
using Server.Misc;

using OSU;
using OSU.Civilizations;

namespace Server.Gumps
{
	public class CivilizationGump : Gump
	{
		//default to Aludia since it is the first one
		private int civ_choice = 0;
		private List<Civilization> all_civilizations = new List<Civilization>();

		private void CivilizationListSetup()
		{
			all_civilizations.Add(Civilizations.Aludia);
			all_civilizations.Add(Civilizations.Durah);
			//daqui pra baixo vão as novas
			all_civilizations.Add(Civilizations.Aludia);
			all_civilizations.Add(Civilizations.Durah);
			all_civilizations.Add(Civilizations.Aludia);
		}

		public CivilizationGump(PlayerMobile m, int target_civ_int = 0) : base(0, 0)
		{
			m.CloseGump(typeof(CivilizationGump));

			this.Closable = false;
			this.Disposable = true;
			this.Dragable = true;
			this.Resizable = false;

			this.CivilizationListSetup();
			civ_choice = target_civ_int;

			AddPage(0);
			AddImage(12, 12, 40322);
			AddLabel(328, 45, 1153, @"Criacao de Personagem");
			AddLabel(113, 99, 1153, @"Povos");
			AddHtml(109, 128, 608, 126, @"<p>TUTORIAL PRA FAZER AS DOIDEIRA DOIDA</p> <a href=https://en.wikipedia.org/wiki/Ultima_Online> CLICA AQUII PRA WIKI</a> ", (bool)false, (bool)true);

			int button_x_pos = 111, label_x_pos = 140;
			int y_position = 331, y_offset = 40;

			for (int civ_index = 0; civ_index < all_civilizations.Count; civ_index++)
			{
				AddButton(button_x_pos, y_position, (civ_index == civ_choice ? 9904 : 9903), (civ_index == civ_choice ? 9903 : 9904), civ_index, GumpButtonType.Reply, 0);
				AddLabel(label_x_pos, y_position, 1153, all_civilizations[civ_index].name);

				y_position += y_offset;
			}

			AddLabel(446, 333, 1153, all_civilizations[civ_choice].title);
			AddHtml(446, 390, 573, 346, all_civilizations[civ_choice].description, (bool)false, (bool)true);

			AddButton(1055, 761, 4005, 4007, 999, GumpButtonType.Reply, 0);
		}
		
		public override void OnResponse(NetState sender, RelayInfo info)
		{
			PlayerMobile m = sender.Mobile as PlayerMobile;

            if( m == null )
                return;

			switch ( info.ButtonID )
			{
				case 999: //setinha de ir pro prox
					CharacterCreationSystem.temp_char.civilization = all_civilizations[civ_choice];
					m.SendGump(new CharStatsGump(m, new CharStats(50), new AvatarDesc(m.Female, 0)));
					m.SendMessage("BOA ESCOLHA!");
					break;
				default:
					civ_choice = info.ButtonID;
					m.SendGump(new CivilizationGump(m, civ_choice));
					m.SendMessage("Selecionou a civilização: " + all_civilizations[civ_choice].name);
					break;
			}
		}
	}
}
