//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////

using System;
using Server;
using Server.Items;
using Server.Network;
using Server.Mobiles;
using Server.Gumps;
using Server.Misc;

using OSU;
using OSU.Civilizations;

namespace Server.Gumps
{
	public class CivilizationGump : Gump
	{
		private int civ_choice = -1;
		
		public CivilizationGump( PlayerMobile m )
			: base( 0, 0 )
		{
			m.CloseGump( typeof(CivilizationGump) );
			this.Closable = false;
			this.Disposable = true;
			this.Dragable = true;
			this.Resizable = false;

			AddPage(0);
			AddImage(0, -3, 40317);
			AddHtml(310, 371, 269, 196, Civilizations.Aludia.description, (bool)false, (bool)true);
			AddHtml(602, 372, 268, 193, Civilizations.Durah.description, (bool)false, (bool)true);
			AddHtml(69, 289, 178, 310, @"<p>Escolha a sua raça seu nóia</p>", (bool)false, (bool)true);

			//Next page
			AddButton(840, 574, 4005, 4007, 0, GumpButtonType.Reply, 0);
			
			AddGroup(0);
			AddLabel(345, 340, 1153, @"Aludia");
			AddRadio(324, 343, 40308, 40310, true, 0);
			AddLabel(647, 340, 1153, @"Durah");
			AddRadio(624, 342, 40308, 40310, false, 1);

		}
		
		public override void OnResponse(NetState sender, RelayInfo info)
		{
			PlayerMobile m = sender.Mobile as PlayerMobile;

            if( m == null )
                return;

			if (info.Switches.Length > 0)
			{
				civ_choice = info.Switches[0];
			}
			else
			{
				civ_choice = -1;
			}

			switch ( info.ButtonID )
			{
				case 0:
					if (civ_choice != -1)
					{
						CharacterCreationSystem.SetCivilization(civ_choice);
						m.SendGump(new CharStatsGump(m));
						m.SendMessage("Selecionou a civilização: " + civ_choice);
					}
					else
					{
						m.SendGump(new CivilizationGump(m));
						m.SendMessage("Não selecionou nenhuma civilização");
					}
					break;
				default:
					m.SendMessage("APERTOU O BOTAO: " + info.ButtonID);
					break;
			}
		}
	}
}
